# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ dev ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
    name: Java ${{ matrix.java }} build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-package: jdk
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir artifacts && cp target/*.jar artifacts
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact.jar
          path: artifacts

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
    name: Java ${{ matrix.java }} Test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

  publish:
#    needs: [ build, test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Publish to Maven Central Repository
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
